Models/ErrorViewModel.cs
namespace EntityEXP02.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Shop.cs
using System.ComponentModel.DataAnnotations;

namespace EntityEXP02.Models
{
    public class Shop
    {

        [Key]
        public string item { get; set; }
        public string color { get; set; }

        public int rate { get; set; }


    }
}

Models/Shop2.cs
using System.ComponentModel.DataAnnotations;

namespace EntityEXP02.Models
{
    public class Shop2
    {

        [Key]
        public string item { get; set; }
        public string color { get; set; }

        public int rate { get; set; }

    }
}

Models/ShopDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace EntityEXP02.Models
{
    public class ShopDbContext : DbContext
    {
        public ShopDbContext(DbContextOptions<ShopDbContext> options) : base(options)
        {
        }

        public DbSet<Shop> Shops { get; set; } // Its create table in ssmdb named "Shops"

        public DbSet<Shop2> Shops2 { get; set; }
    }
}

Controllers/AdminController.cs
using EntityEXP02.Models;
using Microsoft.AspNetCore.Mvc;

namespace EntityEXP02.Controllers
{
    public class AdminController : Controller
    {


        ShopDbContext _context;
        

        public AdminController(ShopDbContext context)
        {
            
            _context = context;


        }



        //public IActionResult Index()
        //{
        //    return View();
        //}
        //public IActionResult Index2()
        //{
        //    return View();
        //}
        //public IActionResult Index3()
        //{
        //    return View();
        //}

        public IActionResult Index4()
        {


            var result = _context.Shops.ToList();
            return View(result);
        }

    }
}

Controllers/HomeController.cs
using EntityEXP02.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EntityEXP02.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/Shop1Controller.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EntityEXP02.Models;

namespace EntityEXP02.Controllers
{
    public class Shop1Controller : Controller
    {
        private readonly ShopDbContext _context;

        public Shop1Controller(ShopDbContext context)
        {
            _context = context;
        }

        // GET: Shop1
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shops.ToListAsync());
        }

        // GET: Shop1/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops
                .FirstOrDefaultAsync(m => m.item == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // GET: Shop1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shop1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("item,color,rate")] Shop shop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shop1/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops.FindAsync(id);
            if (shop == null)
            {
                return NotFound();
            }
            return View(shop);
        }

        // POST: Shop1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("item,color,rate")] Shop shop)
        {
            if (id != shop.item)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShopExists(shop.item))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shop);
        }

        // GET: Shop1/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shop = await _context.Shops
                .FirstOrDefaultAsync(m => m.item == id);
            if (shop == null)
            {
                return NotFound();
            }

            return View(shop);
        }

        // POST: Shop1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var shop = await _context.Shops.FindAsync(id);
            _context.Shops.Remove(shop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShopExists(string id)
        {
            return _context.Shops.Any(e => e.item == id);
        }
    }
}

Controllers/Shop2Controller.cs
using EntityEXP02.Models;
using Microsoft.AspNetCore.Mvc;

namespace EntityEXP02.Controllers
{
    public class Shop2Controller : Controller
    {
        ShopDbContext _context;
       

        public Shop2Controller(ShopDbContext context)
        {
          
            _context = context;


        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AddDetail(Shop2 shops2)
        {

            _context.Add(shops2);
            _context.SaveChanges();


            return View(shops2);
        }

    }
}

Controllers/ShopController.cs
using EntityEXP02.Models;
using EntityEXP02.Utils;
using Microsoft.AspNetCore.Mvc;

namespace EntityEXP02.Controllers
{
    public class ShopController : Controller
    {
        ShopDbContext _context;
        IHelper helper;

        public ShopController(ShopDbContext context, IHelper helper)
        {
            this.helper = helper;
            _context = context;


        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AddDetail(Shop newshop)
        {

            _context.Add(newshop);
            _context.SaveChanges();


            helper.filewrite(newshop);
            
            
            return View(newshop);
        }
    }
}

Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>

Views/Admin/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index2</h1>

Views/Admin/Index3.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Admin/Index4.cshtml
@model IEnumerable<EntityEXP02.Models.Shop>

@{
    ViewData["Title"] = "Index4";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index4</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.rate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.item">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.item">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.item">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>One Page Wonder - Start Bootstrap Template</title>
        <link rel="icon" type="image/x-icon" href="~/Admin/assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container px-5">
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" href="#!">Sign Up</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Log In</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                    <h1 class="masthead-heading mb-0">One Page Wonder</h1>
                    <h2 class="masthead-subheading mb-0">Will Rock Your Socks Off</h2>
                    <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">Learn More</a>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>

        @RenderBody()

         <!-- Content section 1-->
        <section id="scroll">
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="assets/img/01.jpg" alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">For those about to rock...</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 2-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="assets/img/02.jpg" alt="..." /></div>
                    </div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <h2 class="display-4">We salute you!</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Content section 3-->
        <section>
            <div class="container px-5">
                <div class="row gx-5 align-items-center">
                    <div class="col-lg-6 order-lg-2">
                        <div class="p-5"><img class="img-fluid rounded-circle" src="assets/img/03.jpg" alt="..." /></div>
                    </div>
                    <div class="col-lg-6 order-lg-1">
                        <div class="p-5">
                            <h2 class="display-4">Let there be rock!</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione voluptatum molestiae adipisci, beatae obcaecati.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EntityEXP02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EntityEXP02.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EntityEXP02</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EntityEXP02 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shop/Index.cshtml
<html>
    <h1>
        Textail
    </h1>
    <body>
        <form action="AddDetail" method="get">
            Item <input type = "text" name= "item" /> <br />
            Color <input type = "text" name = "color" /><br />
            Price <input type = "text" name = "rate" /><br />
            <input type = "submit" />
        </form>
    </body>
</html>

Views/Shop1/Create.cshtml
@model EntityEXP02.Models.Shop

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Shop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="item" class="control-label"></label>
                <input asp-for="item" class="form-control" />
                <span asp-validation-for="item" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="color" class="control-label"></label>
                <input asp-for="color" class="form-control" />
                <span asp-validation-for="color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rate" class="control-label"></label>
                <input asp-for="rate" class="form-control" />
                <span asp-validation-for="rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shop1/Delete.cshtml
@model EntityEXP02.Models.Shop

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="item" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Shop1/Details.cshtml
@model EntityEXP02.Models.Shop

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Shop</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.rate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.rate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.item">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Shop1/Edit.cshtml
@model EntityEXP02.Models.Shop

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Shop</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="item" />
            <div class="form-group">
                <label asp-for="color" class="control-label"></label>
                <input asp-for="color" class="form-control" />
                <span asp-validation-for="color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rate" class="control-label"></label>
                <input asp-for="rate" class="form-control" />
                <span asp-validation-for="rate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shop1/Index.cshtml
@model IEnumerable<EntityEXP02.Models.Shop>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.rate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.rate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.item">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.item">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.item">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shop2/AddDetail.cshtml
<h1>Success</h1>

Views/Shop2/Index.cshtml
<html>
    <h1>
        Textail
    </h1>
    <body>
      
            <form asp-controller="Shop2" asp-action="AddDetail" method="post">
            Item <input type = "text" name= "item" /> <br />
            Color <input type = "text" name = "color" /><br />
            Price <input type = "text" name = "rate" /><br />
            <input type = "submit" />
        </form>
    </body>
</html>